### ISSUE TITLE
Create base wireframe with functionality

### ISSUE THREAD

**Issue by KosStr** [Levvkubi/TaskAsisstant#14]
Що має бути виконане:
1) Відповідні поля для введення даних.
2) Кнопки для входу та створення облікового запису.
3) Інтерфейс функціональності кнопок.

**Comment by KosStr** [comment]
![image](https://user-images.githubusercontent.com/71460426/94262088-923f5980-ff3b-11ea-996b-e93e99b82fb9.png)

**Comment by KosStr** [comment]
![image](https://user-images.githubusercontent.com/71460426/94262340-01b54900-ff3c-11ea-8a85-a5a438d6f86e.png)
![image](https://user-images.githubusercontent.com/71460426/94262409-1e518100-ff3c-11ea-81e1-8b6634cf1e39.png)
![image](https://user-images.githubusercontent.com/71460426/94262477-3cb77c80-ff3c-11ea-942b-aa511e5aa70f.png)

**Comment by Chernushka9** [comment]
Топ, 10/10
