### ISSUE TITLE
Create prototype based on wireframe

### ISSUE THREAD

**Issue by KosStr** [Levvkubi/TaskAsisstant#15]
![image](https://user-images.githubusercontent.com/71460426/94262910-e72f9f80-ff3c-11ea-85d9-45a90df5b6ee.png)
![image](https://user-images.githubusercontent.com/71460426/94262956-fd3d6000-ff3c-11ea-8a22-f1fe986148c2.png)
![image](https://user-images.githubusercontent.com/71460426/94262976-062e3180-ff3d-11ea-8c83-ccfcd9a6d153.png)

**Comment by Chernushka9** [comment]
![2](https://user-images.githubusercontent.com/65550114/93874438-0aa7df80-fcdc-11ea-81f8-b09ba6e0dcf5.jpg)
![3](https://user-images.githubusercontent.com/65550114/93874445-0e3b6680-fcdc-11ea-996f-622bc77ee2a0.jpg)

**Comment by KosStr** [comment]
Завдання виконано бездоганно
