### ISSUE TITLE
Generate values for "tasks" and "users"

### ISSUE THREAD

**Issue by KosStr** [Levvkubi/TaskAsisstant#24]

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711689-14d0b100-1ac6-11eb-9771-b560939552ad.png)

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711899-582b1f80-1ac6-11eb-8c52-70292ff97ccb.png)

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711922-624d1e00-1ac6-11eb-95a2-de6fff6506a4.png)
