### ISSUE TITLE
Hash password in PostgreSQL

### ISSUE THREAD

**Issue by KosStr** [Levvkubi/TaskAsisstant#25]

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711210-79d7d700-1ac5-11eb-8cad-242f3456080f.png)

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711305-9a079600-1ac5-11eb-8ec2-e8a13b51ebb3.png)

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711328-a12ea400-1ac5-11eb-86d8-2350e71b5e04.png)

**Comment by Levvkubi** [comment]
![image](https://user-images.githubusercontent.com/63650453/97711619-fc609680-1ac5-11eb-8e30-420d0d911760.png)
